import 'package:flutter/material.dart';
import 'package:soul_tunes/utils/constants/sizes.dart';
import 'package:soul_tunes/utils/constants/text_strings.dart';
import 'package:soul_tunes/utils/helpers/helper_functions.dart';

class SuccessScreen extends StatelessWidget {
  const SuccessScreen(
      {super.key,
      required this.title,
      required this.subtitle,
      required this.image,
      required this.onPressed});

  final String title, subtitle, image;
  final VoidCallback onPressed;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(
            SSizes.defaultSpace,
          ),
          child: Column(
            children: [
              const SizedBox(
                height: SSizes.spaceBtwSections * 2,
              ),
              Image(
                image: AssetImage(image),
                width: SHelperFunctions.screenWidth() * 0.8,
              ),
              const SizedBox(
                height: SSizes.spaceBtwSections,
              ),

              //title and subtitle

              Text(
                title,
                style: Theme.of(context).textTheme.headlineMedium,
                textAlign: TextAlign.center,
              ),
              const SizedBox(
                height: SSizes.spaceBtwItems,
              ),

              Text(
                subtitle,
                style: Theme.of(context).textTheme.bodyLarge,
                textAlign: TextAlign.center,
              ),
              const SizedBox(
                height: SSizes.spaceBtwItems,
              ),

              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                    onPressed: onPressed, child: const Text(STexts.tContinue)),
              ),
              const SizedBox(
                height: SSizes.spaceBtwItems,
              ),
            ],
          ),
        ),
      ),
    );
  }
}







// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDl-D3BCN69iyKdyoU9aGPPVkhhBRJrrE8',
//     appId: '1:445898123738:web:37cb2894f86a7864b6b8e3',
//     messagingSenderId: '445898123738',
//     projectId: 'fcc-new-project',
//     authDomain: 'fcc-new-project.firebaseapp.com',
//     storageBucket: 'fcc-new-project.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBK6maAn-HI3JFE1AN60Rx-rPyjCimjOvQ',
//     appId: '1:445898123738:android:7c3048b31a59b89bb6b8e3',
//     messagingSenderId: '445898123738',
//     projectId: 'fcc-new-project',
//     storageBucket: 'fcc-new-project.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBfikGwvr4GT3UsxVVGJqSUqrOgOlQCLk0',
//     appId: '1:445898123738:ios:6886918870cfc684b6b8e3',
//     messagingSenderId: '445898123738',
//     projectId: 'fcc-new-project',
//     storageBucket: 'fcc-new-project.appspot.com',
//     iosBundleId: 'com.example.fcc',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBfikGwvr4GT3UsxVVGJqSUqrOgOlQCLk0',
//     appId: '1:445898123738:ios:b987f102bcc9ad6fb6b8e3',
//     messagingSenderId: '445898123738',
//     projectId: 'fcc-new-project',
//     storageBucket: 'fcc-new-project.appspot.com',
//     iosBundleId: 'com.example.fcc.RunnerTests',
//   );
// }
