// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARURtQ6eWHRr-UkTWoZVzt4XoGix891Mo',
    appId: '1:108879998314:web:5993a62aac3b8196748913',
    messagingSenderId: '108879998314',
    projectId: 'rhythmiq-sahana',
    authDomain: 'rhythmiq-sahana.firebaseapp.com',
    storageBucket: 'rhythmiq-sahana.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4WoMJziG-cmNq6DAdHpRSBfB5mgnxU98',
    appId: '1:108879998314:android:04d2ca1ceed72152748913',
    messagingSenderId: '108879998314',
    projectId: 'rhythmiq-sahana',
    storageBucket: 'rhythmiq-sahana.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARURtQ6eWHRr-UkTWoZVzt4XoGix891Mo',
    appId: '1:108879998314:web:4c992d7bcad9ba23748913',
    messagingSenderId: '108879998314',
    projectId: 'rhythmiq-sahana',
    authDomain: 'rhythmiq-sahana.firebaseapp.com',
    storageBucket: 'rhythmiq-sahana.appspot.com',
  );

}