import 'package:soul_tunes/utils/constants/image_strings.dart';

class GridMaps {
  GridMaps();
  static List<int> index2 = [];
  static List<int> myorders = [];
  static const List<Map<String, dynamic>> gridMap = [
    {
      "title": "Yamaha Guitar",
      "saleprice": "6000 Rs",
      "images": SImages.guitar2,
      "brand": "Gibson",
      "finalprice": 5000,
      "ratings": "5",
      "discount": "16%",
    },
    {
      "title": "Flute-G1",
      "saleprice": "2000 Rs",
      "images": SImages.flute1,
      "brand": "Gibson",
      "finalprice": 1800,
      "ratings": "5",
      "discount": "10%",
    },
    {
      "title": "GuitarLight",
      "saleprice": "6000 Rs",
      "images": SImages.guitarLight,
      "brand": "Yamaha",
      "finalprice": 5000,
      "ratings": "5",
      "discount": "16%",
    },
    {
      "title": "Saxophone-XUV5",
      "saleprice": "6000 Rs",
      "images": SImages.saxophoneVertical,
      "brand": "Yamaha",
      "finalprice": 5000,
      "ratings": "4.5",
      "discount": "15%",
    },
    {
      "title": "Saxophone-XUV6",
      "saleprice": "4000 Rs",
      "images": SImages.saxophone3,
      "brand": "Gibson",
      "finalprice": 3600,
      "ratings": "5",
      "discount": "10%",
    },
    {
      "title": "Violin",
      "saleprice": "7890 Rs",
      "images": SImages.violin1,
      "brand": "Roland",
      "finalprice": 6627,
      "ratings": "4.5",
      "discount": "16%",
    },
    {
      "title": "Mandolin",
      "saleprice": "7890 Rs",
      "images": SImages.mandolin_1,
      "brand": "Roland",
      "finalprice": 6627,
      "ratings": "4.5",
      "discount": "16%",
    },
    {
      "title": "Flute",
      "saleprice": "1890 Rs",
      "images": SImages.flute2,
      "brand": "Roland",
      "finalprice": 6627,
      "ratings": "4.5",
      "discount": "16%",
    },
    {
      "title": "Flute",
      "saleprice": "7890 Rs",
      "images": SImages.flute3,
      "brand": "Roland",
      "finalprice": 6627,
      "ratings": "4.5",
      "discount": "16%",
    },
    {
      "title": "Violin-GFR",
      "saleprice": "7000 Rs",
      "images": SImages.violin_1,
      "brand": "Yamaha",
      "finalprice": 6000,
      "ratings": "5",
      "discount": "15%",
    },
    {
      "title": "Clariet",
      "saleprice": "7000 Rs",
      "images": SImages.clariet_1,
      "brand": "Yamaha",
      "finalprice": 6000,
      "ratings": "5",
      "discount": "15%",
    },
    {
      "title": "Saxophone-AMF",
      "saleprice": "7000 Rs",
      "images": SImages.saxophone2,
      "brand": "Yamaha",
      "finalprice": 6000,
      "ratings": "4.5",
      "discount": "15%",
    },
    {
      "title": "Violin-GF",
      "saleprice": "6000 Rs",
      "images": SImages.violin2,
      "brand": "Yamaha",
      "finalprice": 5000,
      "ratings": "4.1",
      "discount": "16%",
    },
    {
      "title": "Chinesedrum",
      "saleprice": "7000 Rs",
      "images": SImages.chinesedrum,
      "brand": "Yamaha",
      "finalprice": 6000,
      "ratings": "4.0",
      "discount": "15%",
    },
    {
      "title": "Clariet",
      "saleprice": "6000 Rs",
      "images": SImages.clariett,
      "brand": "Yamaha",
      "finalprice": 5000,
      "ratings": "4.6",
      "discount": "16%",
    },
    {
      "title": "Djembe",
      "saleprice": "7000 Rs",
      "images": SImages.djembe2,
      "brand": "Yamaha",
      "finalprice": 6000,
      "ratings": "3.6",
      "discount": "15%",
    },
    {
      "title": "Piano",
      "saleprice": "9000 Rs",
      "images": SImages.pianoo,
      "brand": "Yamaha",
      "finalprice": 7650,
      "ratings": "4.5",
      "discount": "15%",
    },
    {
      "title": "Djembe Iconic",
      "saleprice": "8000 Rs",
      "images": SImages.djembe,
      "brand": "Yamaha",
      "finalprice": 6800,
      "ratings": "4.5",
      "discount": "15%",
    },
  ];
}
